# Pandas query() Method - Answer Key

Complete solutions for all exercises with both `loc[]` and `query()` versions.

## Setup: Run this cell first

In [1]:
import pandas as pd
import numpy as np

# Dataset 1: Employee Data
employees = pd.DataFrame({
    'employee_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'name': ['Alice Johnson', 'Bob Smith', 'Charlie Brown', 'Diana Prince', 
             'Edward Norton', 'Fiona Apple', 'George Martin', 'Helen Troy', 
             'Ian Malcolm', 'Jane Doe'],
    'age': [28, 35, 42, 31, 29, 38, 45, 33, 41, 27],
    'department': ['Engineering', 'Sales', 'Engineering', 'HR', 'Sales', 
                   'Engineering', 'HR', 'Sales', 'Engineering', 'HR'],
    'salary': [75000, 65000, 95000, 60000, 68000, 82000, 70000, 72000, 88000, 58000],
    'years_experience': [5, 12, 18, 8, 6, 14, 20, 10, 16, 4]
})

# Dataset 2: Product Sales Data
products = pd.DataFrame({
    'product_id': ['P001', 'P002', 'P003', 'P004', 'P005', 'P006', 'P007', 'P008'],
    'product_name': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Headphones', 
                     'Webcam', 'Speaker', 'Microphone'],
    'category': ['Electronics', 'Accessories', 'Accessories', 'Electronics', 
                 'Accessories', 'Electronics', 'Accessories', 'Electronics'],
    'price': [1200, 25, 75, 350, 150, 80, 120, 95],
    'stock': [45, 200, 150, 80, 120, 95, 60, 110],
    'rating': [4.5, 4.2, 4.0, 4.7, 4.3, 3.9, 4.1, 4.4]
})

print("Datasets created successfully!")
display(employees)
display(products)

Datasets created successfully!

   employee_id           name  age   department  salary  years_experience
0          101  Alice Johnson   28  Engineering   75000                 5
1          102      Bob Smith   35        Sales   65000                12
2          103  Charlie Brown   42  Engineering   95000                18
3          104   Diana Prince   31           HR   60000                 8
4          105  Edward Norton   29        Sales   68000                 6
5          106    Fiona Apple   38  Engineering   82000                14
6          107  George Martin   45           HR   70000                20
7          108     Helen Troy   33        Sales   72000                10
8          109    Ian Malcolm   41  Engineering   88000                16
9          110       Jane Doe   27           HR   58000                 4

  product_id product_name     category  price  stock  rating
0       P001       Laptop  Electronics   1200     45     4.5
1       P002        Mouse  Accessories     25    200     4.2
2       P003     Keyboard  Accessories     75    150     4.0
3       P004      Monitor  Electronics    350     80     4.7
4       P005   Headphones  Accessories    150    120     4.3
5       P006       Webcam  Electronics     80     95     3.9
6       P007      Speaker  Accessories    120     60     4.1
7       P008   Microphone  Electronics     95    110     4.4

## Part 1: Basic Filtering

### Exercise 1.1: Filter employees older than 35

In [2]:
# Using loc[]
result_loc = employees.loc[employees['age'] > 35]
print("Using loc[]:")
display(result_loc)

Using loc[]:

   employee_id           name  age   department  salary  years_experience
2          103  Charlie Brown   42  Engineering   95000                18
5          106    Fiona Apple   38  Engineering   82000                14
6          107  George Martin   45           HR   70000                20
8          109    Ian Malcolm   41  Engineering   88000                16

In [3]:
mask = employees['age']>35
mask
employees.loc[mask]

   employee_id           name  age   department  salary  years_experience
2          103  Charlie Brown   42  Engineering   95000                18
5          106    Fiona Apple   38  Engineering   82000                14
6          107  George Martin   45           HR   70000                20
8          109    Ian Malcolm   41  Engineering   88000                16

In [4]:
type(employees['age'])
stat_emp = employees[['name','age','salary']]
stat_emp

            name  age  salary
0  Alice Johnson   28   75000
1      Bob Smith   35   65000
2  Charlie Brown   42   95000
3   Diana Prince   31   60000
4  Edward Norton   29   68000
5    Fiona Apple   38   82000
6  George Martin   45   70000
7     Helen Troy   33   72000
8    Ian Malcolm   41   88000
9       Jane Doe   27   58000

In [5]:
# Using query()
result_query = employees.query('age > 35') #needs to be a string
print("Using query():")
display(result_query)

Using query():

   employee_id           name  age   department  salary  years_experience
2          103  Charlie Brown   42  Engineering   95000                18
5          106    Fiona Apple   38  Engineering   82000                14
6          107  George Martin   45           HR   70000                20
8          109    Ian Malcolm   41  Engineering   88000                16

### Exercise 1.2: Filter products with price less than or equal to 100

In [6]:
# Using loc[]
result_loc = products.loc[products['price'] <= 100]
print("Using loc[]:")
display(result_loc)

Using loc[]:

  product_id product_name     category  price  stock  rating
1       P002        Mouse  Accessories     25    200     4.2
2       P003     Keyboard  Accessories     75    150     4.0
5       P006       Webcam  Electronics     80     95     3.9
7       P008   Microphone  Electronics     95    110     4.4

In [7]:
# Using query()

result_query = products.loc[(products['price'] <= 100) | (products['category'] == 'Eletronics')]


print("Using query():")
display(result_query)

Using query():

  product_id product_name     category  price  stock  rating
1       P002        Mouse  Accessories     25    200     4.2
2       P003     Keyboard  Accessories     75    150     4.0
5       P006       Webcam  Electronics     80     95     3.9
7       P008   Microphone  Electronics     95    110     4.4

In [8]:
products.loc[(products['price'] <= 100)]

  product_id product_name     category  price  stock  rating
1       P002        Mouse  Accessories     25    200     4.2
2       P003     Keyboard  Accessories     75    150     4.0
5       P006       Webcam  Electronics     80     95     3.9
7       P008   Microphone  Electronics     95    110     4.4

In [9]:
products.loc[(products['category'] == 'Eletronics')]

Empty DataFrame
Columns: [product_id, product_name, category, price, stock, rating]
Index: []

### Exercise 1.3: Filter employees with exactly 10 years of experience

In [10]:
# Using loc[]
result_loc = employees.loc[(employees['years_experience'] < 10) & (employees['department'] =='HR')]
print("Using loc[]:")
display(result_loc)

Using loc[]:

   employee_id          name  age department  salary  years_experience
3          104  Diana Prince   31         HR   60000                 8
9          110      Jane Doe   27         HR   58000                 4

In [11]:
# Using query()
result_query = employees.query('years_experience < 10 and department == "HR"')
print("Using query():")
display(result_query)

Using query():

   employee_id          name  age department  salary  years_experience
3          104  Diana Prince   31         HR   60000                 8
9          110      Jane Doe   27         HR   58000                 4

## Part 2: Multiple Conditions

### Exercise 2.1: Filter employees in Engineering department with salary > 80000

In [12]:
# Using loc[]
result_loc = employees.loc[(employees['department'] == 'Engineering') & 
                            (employees['salary'] > 80000) &
                            (employees['salary'] < 95000)]
print("Using loc[]:")
display(result_loc)

Using loc[]:

   employee_id         name  age   department  salary  years_experience
5          106  Fiona Apple   38  Engineering   82000                14
8          109  Ian Malcolm   41  Engineering   88000                16

In [13]:
# Using query()
result_query = employees.query('department == "Engineering" and salary > 80000 and salary < 95000')
print("Using query():")
display(result_query)

Using query():

   employee_id         name  age   department  salary  years_experience
5          106  Fiona Apple   38  Engineering   82000                14
8          109  Ian Malcolm   41  Engineering   88000                16

### Exercise 2.2: Filter products that are Electronics AND have rating >= 4.5

In [14]:
# Using loc[]
result_loc = products.loc[(products['category'] == 'Electronics') & 
                           (products['rating'] >= 4.5)]
print("Using loc[]:")
display(result_loc)

Using loc[]:

  product_id product_name     category  price  stock  rating
0       P001       Laptop  Electronics   1200     45     4.5
3       P004      Monitor  Electronics    350     80     4.7

In [15]:
# Using query()
result_query = products.query('category == "Electronics" and rating >= 4.5')
print("Using query():")
display(result_query)

Using query():

  product_id product_name     category  price  stock  rating
0       P001       Laptop  Electronics   1200     45     4.5
3       P004      Monitor  Electronics    350     80     4.7

### Exercise 2.3: Filter employees who are either younger than 30 OR have salary > 85000

In [16]:
# Using loc[]
result_loc = employees.loc[(employees['age'] < 30) | (employees['salary'] > 85000)]
print("Using loc[]:")
display(result_loc)

Using loc[]:

   employee_id           name  age   department  salary  years_experience
0          101  Alice Johnson   28  Engineering   75000                 5
2          103  Charlie Brown   42  Engineering   95000                18
4          105  Edward Norton   29        Sales   68000                 6
8          109    Ian Malcolm   41  Engineering   88000                16
9          110       Jane Doe   27           HR   58000                 4

In [17]:
# Using query()
result_query = employees.query('age < 30 or salary > 85000')
print("Using query():")
display(result_query)

Using query():

   employee_id           name  age   department  salary  years_experience
0          101  Alice Johnson   28  Engineering   75000                 5
2          103  Charlie Brown   42  Engineering   95000                18
4          105  Edward Norton   29        Sales   68000                 6
8          109    Ian Malcolm   41  Engineering   88000                16
9          110       Jane Doe   27           HR   58000                 4

## Part 3: Using Variables

### Exercise 3.1: Filter employees with age between min_age and max_age (inclusive)

In [18]:
min_age = 30
max_age = 40

# Using loc[]
result_loc = employees.loc[(employees['age'] >= min_age) & 
                            (employees['age'] <= max_age)]
print("Using loc[]:")
display(result_loc)

Using loc[]:

   employee_id          name  age   department  salary  years_experience
1          102     Bob Smith   35        Sales   65000                12
3          104  Diana Prince   31           HR   60000                 8
5          106   Fiona Apple   38  Engineering   82000                14
7          108    Helen Troy   33        Sales   72000                10

In [19]:
# Using query()
result_query = employees.query('age >= @min_age and age <= @max_age')
print("Using query():")
display(result_query)

Using query():

   employee_id          name  age   department  salary  years_experience
1          102     Bob Smith   35        Sales   65000                12
3          104  Diana Prince   31           HR   60000                 8
5          106   Fiona Apple   38  Engineering   82000                14
7          108    Helen Troy   33        Sales   72000                10

In [20]:

result_query = employees.query('age >= @min_age and age <= @max_age')
print("Using query():")

display(result_query)

Using query():

   employee_id          name  age   department  salary  years_experience
1          102     Bob Smith   35        Sales   65000                12
3          104  Diana Prince   31           HR   60000                 8
5          106   Fiona Apple   38  Engineering   82000                14
7          108    Helen Troy   33        Sales   72000                10

In [21]:

result_query = employees.loc[employees['age'].between(min_age, max_age)]
display(result_query)

   employee_id          name  age   department  salary  years_experience
1          102     Bob Smith   35        Sales   65000                12
3          104  Diana Prince   31           HR   60000                 8
5          106   Fiona Apple   38  Engineering   82000                14
7          108    Helen Troy   33        Sales   72000                10

### Exercise 3.2: Filter products with stock below threshold

In [22]:
stock_threshold = 100

# Using loc[]
result_loc = products.loc[products['stock'] < stock_threshold]
print("Using loc[]:")
display(result_loc)

Using loc[]:

  product_id product_name     category  price  stock  rating
0       P001       Laptop  Electronics   1200     45     4.5
3       P004      Monitor  Electronics    350     80     4.7
5       P006       Webcam  Electronics     80     95     3.9
6       P007      Speaker  Accessories    120     60     4.1

In [23]:
# Using query()
result_query = products.query('stock < @stock_threshold')
print("Using query():")
display(result_query)

Using query():

  product_id product_name     category  price  stock  rating
0       P001       Laptop  Electronics   1200     45     4.5
3       P004      Monitor  Electronics    350     80     4.7
5       P006       Webcam  Electronics     80     95     3.9
6       P007      Speaker  Accessories    120     60     4.1

### Exercise 3.3: Filter employees with salary in a specific range

In [24]:
min_salary = 65000
max_salary = 80000

# Using loc[]
result_loc = employees.loc[(employees['salary'] >= min_salary) & 
                            (employees['salary'] <= max_salary)]
print("Using loc[]:")
display(result_loc)

Using loc[]:

   employee_id           name  age   department  salary  years_experience
0          101  Alice Johnson   28  Engineering   75000                 5
1          102      Bob Smith   35        Sales   65000                12
4          105  Edward Norton   29        Sales   68000                 6
6          107  George Martin   45           HR   70000                20
7          108     Helen Troy   33        Sales   72000                10

In [25]:
# Using query()
result_query = employees.query('salary >= @min_salary and salary <= @max_salary')
print("Using query():")
display(result_query)

Using query():

   employee_id           name  age   department  salary  years_experience
0          101  Alice Johnson   28  Engineering   75000                 5
1          102      Bob Smith   35        Sales   65000                12
4          105  Edward Norton   29        Sales   68000                 6
6          107  George Martin   45           HR   70000                20
7          108     Helen Troy   33        Sales   72000                10

## Part 4: String Operations

### Exercise 4.1: Filter employees whose name starts with a letter from A-E

In [26]:
# Using loc[]
result_loc = employees.loc[employees['name'].str[0] <= 'E']
print("Using loc[]:")
display(result_loc)

Using loc[]:

   employee_id           name  age   department  salary  years_experience
0          101  Alice Johnson   28  Engineering   75000                 5
1          102      Bob Smith   35        Sales   65000                12
2          103  Charlie Brown   42  Engineering   95000                18
3          104   Diana Prince   31           HR   60000                 8
4          105  Edward Norton   29        Sales   68000                 6

In [48]:
# Using query()
result_query = employees.query('name.str[0] == "E"')
print("Using query():")
display(result_query)

Using query():

   employee_id           name  age   department  salary  years_experience
0          101  Alice Johnson   28  Engineering   75000                 5
1          102      Bob Smith   35        Sales   65000                12
2          103  Charlie Brown   42  Engineering   95000                18
3          104   Diana Prince   31           HR   60000                 8
4          105  Edward Norton   29        Sales   68000                 6

In [50]:
employees['name'].str[0]<= 'E'

0     True
1     True
2     True
3     True
4     True
5    False
6    False
7    False
8    False
9    False
Name: name, dtype: bool

### Exercise 4.2: Filter products whose name contains the word 'phone' (case-insensitive)

In [83]:
# Using loc[]
mask1 = products['product_name'].str.lower().str.contains('phone')
mask2 = products['product_name'].str.contains('phone', case=False)
result_loc = products.loc[mask2]
print("Using loc[]:")
display(result_loc)

Using loc[]:

  product_id product_name     category  price  stock  rating
4       P005   Headphones  Accessories    150    120     4.3
7       P008   Microphone  Electronics     95    110     4.4

In [63]:
products['product_name'].str.lower().str.contains('phone')

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7     True
Name: product_name, dtype: bool

In [84]:
# Using query()
p = "Phone".lower()
result_query = products.query('product_name.str.contains("phone", case=False)')
print("Using query():")
display(result_query)

Using query():

  product_id product_name     category  price  stock  rating
4       P005   Headphones  Accessories    150    120     4.3
7       P008   Microphone  Electronics     95    110     4.4

In [88]:
p = "PhOne".lower()
result_query = products.query('product_name.str.lower().str.contains(@p)') #query needs @
print(p)

phone

## Part 5: Using 'in' operator

### Exercise 5.1: Filter employees in either Sales or HR departments

In [78]:
target_departments = ['Sales', 'HR']
employees['department'].isin(target_departments)

0    False
1     True
2    False
3     True
4     True
5    False
6     True
7     True
8    False
9     True
Name: department, dtype: bool

In [80]:
employees['department'].values_counts()

AttributeError: 'Series' object has no attribute 'values_counts'

In [31]:
# Using query()
result_query = employees.query('department in @target_departments')
print("Using query():")
display(result_query)

Using query():

   employee_id           name  age department  salary  years_experience
1          102      Bob Smith   35      Sales   65000                12
3          104   Diana Prince   31         HR   60000                 8
4          105  Edward Norton   29      Sales   68000                 6
6          107  George Martin   45         HR   70000                20
7          108     Helen Troy   33      Sales   72000                10
9          110       Jane Doe   27         HR   58000                 4

### Exercise 5.2: Filter products in a list of product IDs

In [32]:
target_products = ['P001', 'P003', 'P005', 'P007']

# Using loc[]
result_loc = products.loc[products['product_id'].isin(target_products)]
print("Using loc[]:")
display(result_loc)

Using loc[]:

  product_id product_name     category  price  stock  rating
0       P001       Laptop  Electronics   1200     45     4.5
2       P003     Keyboard  Accessories     75    150     4.0
4       P005   Headphones  Accessories    150    120     4.3
6       P007      Speaker  Accessories    120     60     4.1

In [33]:
# Using query()
result_query = products.query('product_id in @target_products')
print("Using query():")
display(result_query)

Using query():

  product_id product_name     category  price  stock  rating
0       P001       Laptop  Electronics   1200     45     4.5
2       P003     Keyboard  Accessories     75    150     4.0
4       P005   Headphones  Accessories    150    120     4.3
6       P007      Speaker  Accessories    120     60     4.1

## Part 6: Complex Queries

### Exercise 6.1: Filter employees in Engineering, over 35, and earning more than 80000

In [34]:
# Using loc[]
result_loc = employees.loc[(employees['department'] == 'Engineering') & 
                            (employees['age'] > 35) & 
                            (employees['salary'] > 80000)]
print("Using loc[]:")
display(result_loc)

Using loc[]:

   employee_id           name  age   department  salary  years_experience
2          103  Charlie Brown   42  Engineering   95000                18
5          106    Fiona Apple   38  Engineering   82000                14
8          109    Ian Malcolm   41  Engineering   88000                16

In [35]:
# Using query()
result_query = employees.query('department == "Engineering" and age > 35 and salary > 80000')
print("Using query():")
display(result_query)

Using query():

   employee_id           name  age   department  salary  years_experience
2          103  Charlie Brown   42  Engineering   95000                18
5          106    Fiona Apple   38  Engineering   82000                14
8          109    Ian Malcolm   41  Engineering   88000                16

### Exercise 6.2: Filter products that are either:
- In Electronics category with rating >= 4.5, OR
- Priced under 100 with stock > 100

In [36]:
# Using loc[]
result_loc = products.loc[((products['category'] == 'Electronics') & 
                            (products['rating'] >= 4.5)) |
                           ((products['price'] < 100) & 
                            (products['stock'] > 100))]
print("Using loc[]:")
display(result_loc)

Using loc[]:

  product_id product_name     category  price  stock  rating
0       P001       Laptop  Electronics   1200     45     4.5
1       P002        Mouse  Accessories     25    200     4.2
2       P003     Keyboard  Accessories     75    150     4.0
3       P004      Monitor  Electronics    350     80     4.7
7       P008   Microphone  Electronics     95    110     4.4

In [37]:
# Using query()
result_query = products.query('(category == "Electronics" and rating >= 4.5) or (price < 100 and stock > 100)')
print("Using query():")
display(result_query)

Using query():

  product_id product_name     category  price  stock  rating
0       P001       Laptop  Electronics   1200     45     4.5
1       P002        Mouse  Accessories     25    200     4.2
2       P003     Keyboard  Accessories     75    150     4.0
3       P004      Monitor  Electronics    350     80     4.7
7       P008   Microphone  Electronics     95    110     4.4

### Exercise 6.3: Filter employees who have:
- More than 10 years experience AND salary < 75000, OR
- Less than 5 years experience AND salary > 70000

In [38]:
# Using loc[]
result_loc = employees.loc[((employees['years_experience'] > 10) & 
                             (employees['salary'] < 75000)) |
                            ((employees['years_experience'] < 5) & 
                             (employees['salary'] > 70000))]
print("Using loc[]:")
display(result_loc)

Using loc[]:

   employee_id           name  age department  salary  years_experience
1          102      Bob Smith   35      Sales   65000                12
6          107  George Martin   45         HR   70000                20

In [39]:
# Using query()
result_query = employees.query('(years_experience > 10 and salary < 75000) or (years_experience < 5 and salary > 70000)')
print("Using query():")
display(result_query)

Using query():

   employee_id           name  age department  salary  years_experience
1          102      Bob Smith   35      Sales   65000                12
6          107  George Martin   45         HR   70000                20

## Challenge Exercises

### Challenge 1: Find 'underpaid' employees
Definition: More than 15 years experience but salary less than 80000

In [40]:
# use either query() or loc

### Challenge 2: Find 'premium' products
Definition: Electronics category, rating > 4.0, price > 200, and stock < 100

In [41]:
# use either query() or loc

### Challenge 3: Complex employee search
Find employees whose:
- Name contains 'a' or 'e' (case-insensitive)
- Age is between 30-40 (use variables)
- Department is not HR
- Salary is above the median salary

In [42]:
# use either query() or loc

## Key Takeaways

### Readability Comparison
Notice how `query()` becomes increasingly valuable as conditions grow more complex:
- Simple filters: Both methods are equally readable
- Multiple conditions: `query()` starts to shine (no need for parentheses around each condition)
- Complex logic: `query()` is significantly cleaner and more maintainable

### When to Use Each Method

**Use `query()`:**
- Multiple filtering conditions
- Complex logical expressions
- When code readability is important
- For SQL-like syntax preference

**Use `loc[]`:**
- When you need to modify/assign values
- Single simple conditions
- When working with boolean Series from complex operations

### Performance Notes
- For most datasets, performance is comparable
- `query()` may have slight advantages on very large DataFrames
- Both methods create copies of data (important for memory considerations)

### Common Pitfalls to Avoid
1. Forgetting quotes around string values in `query()`
2. Forgetting `@` symbol when referencing variables in `query()`
3. Missing parentheses around conditions when using `&` or `|` in `loc[]`
4. Trying to use `query()` for assignment operations (use `loc[]` instead)