In [7]:
import numpy as np
import pandas as pd

from pandas import DataFrame

In [28]:
numbers_df = DataFrame(np.arange(0,90,3).reshape(10,3), 
                       index = ['row1','row2','row3','row4','row5','row6','row7','row8','row9','row10'], columns = ['column1', 'column2','column3'])

numbers_df

       column1  column2  column3
row1         0        3        6
row2         9       12       15
row3        18       21       24
row4        27       30       33
row5        36       39       42
row6        45       48       51
row7        54       57       60
row8        63       66       69
row9        72       75       78
row10       81       84       87

In [29]:
numbers_df.iloc[0,1]

np.int64(3)

In [30]:
numbers_df.iloc[0,1] = 20

In [31]:
numbers_df

       column1  column2  column3
row1         0       20        6
row2         9       12       15
row3        18       21       24
row4        27       30       33
row5        36       39       42
row6        45       48       51
row7        54       57       60
row8        63       66       69
row9        72       75       78
row10       81       84       87

In [32]:
numbers_df.iloc[[1,2,4],[1,2]]

      column2  column3
row2       12       15
row3       21       24
row5       39       42

In [33]:
mask = numbers_df >30
mask

       column1  column2  column3
row1     False    False    False
row2     False    False    False
row3     False    False    False
row4     False    False     True
row5      True     True     True
row6      True     True     True
row7      True     True     True
row8      True     True     True
row9      True     True     True
row10     True     True     True

In [34]:
numbers_df[mask]

       column1  column2  column3
row1       NaN      NaN      NaN
row2       NaN      NaN      NaN
row3       NaN      NaN      NaN
row4       NaN      NaN     33.0
row5      36.0     39.0     42.0
row6      45.0     48.0     51.0
row7      54.0     57.0     60.0
row8      63.0     66.0     69.0
row9      72.0     75.0     78.0
row10     81.0     84.0     87.0

In [35]:
numbers_df[numbers_df>30] = 0
numbers_df

       column1  column2  column3
row1         0       20        6
row2         9       12       15
row3        18       21       24
row4        27       30        0
row5         0        0        0
row6         0        0        0
row7         0        0        0
row8         0        0        0
row9         0        0        0
row10        0        0        0

In [37]:
numbers_df.iloc[2:6,1:3]

      column2  column3
row3       21       24
row4       30        0
row5        0        0
row6        0        0

In [40]:
data = {'names': ['steve', 'john', 'richard', 'sarah','randy','michael','julie'],
       'age': [20,22,20,21,24,23,22],
        'gender': ['male','male','male','female','male','male','female'],
        'rank': [2,1,4,5,3,7,6]
       }

ranking_df = DataFrame(data)
ranking_df.iloc[2:5,1] = np.nan
ranking_df.iloc[3:6,3] = np.nan
ranking_df.iloc[3,:] = np.nan
ranking_df

     names   age  gender  rank
0    steve  20.0    male   2.0
1     john  22.0    male   1.0
2  richard   NaN    male   4.0
3      NaN   NaN     NaN   NaN
4    randy   NaN    male   NaN
5  michael  23.0    male   NaN
6    julie  22.0  female   6.0

In [42]:
ranking_df.isnull()

   names    age  gender   rank
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3   True   True    True   True
4  False   True   False   True
5  False  False   False   True
6  False  False   False  False

In [44]:
ranking_df.notnull()

   names    age  gender   rank
0   True   True    True   True
1   True   True    True   True
2   True  False    True   True
3  False  False   False  False
4   True  False    True  False
5   True   True    True  False
6   True   True    True   True

In [46]:
bool_series = pd.isnull(ranking_df['age'])
ranking_df[bool_series]

     names  age gender  rank
2  richard  NaN   male   4.0
3      NaN  NaN    NaN   NaN
4    randy  NaN   male   NaN

In [55]:
ranking_df.fillna(0)

     names   age  gender  rank
0    steve  20.0    male   2.0
1     john  22.0    male   1.0
2  richard   0.0    male   4.0
3        0   0.0       0   0.0
4    randy   0.0    male   0.0
5  michael  23.0    male   0.0
6    julie  22.0  female   6.0

In [57]:
ranking_df.bfill()

     names   age  gender  rank
0    steve  20.0    male   2.0
1     john  22.0    male   1.0
2  richard  23.0    male   4.0
3    randy  23.0    male   6.0
4    randy  23.0    male   6.0
5  michael  23.0    male   6.0
6    julie  22.0  female   6.0

In [58]:
ranking_df.ffill()

     names   age  gender  rank
0    steve  20.0    male   2.0
1     john  22.0    male   1.0
2  richard  22.0    male   4.0
3  richard  22.0    male   4.0
4    randy  22.0    male   4.0
5  michael  23.0    male   4.0
6    julie  22.0  female   6.0

In [60]:
ranking_df.interpolate(method = 'linear')

C:\Users\biauser\AppData\Local\Temp\ipykernel_8220\3896898724.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  ranking_df.interpolate(method = 'linear')

     names    age  gender  rank
0    steve  20.00    male   2.0
1     john  22.00    male   1.0
2  richard  22.25    male   4.0
3      NaN  22.50     NaN   4.5
4    randy  22.75    male   5.0
5  michael  23.00    male   5.5
6    julie  22.00  female   6.0

In [62]:
ranking_df.dropna()

   names   age  gender  rank
0  steve  20.0    male   2.0
1   john  22.0    male   1.0
6  julie  22.0  female   6.0

In [63]:
from pandas import Series, DataFrame

In [66]:
DF_obj = DataFrame({'column1': [1,1,2,2,3,3,3],
                    'column2': ['a','a','b','b','c','c','c'],
                    'column3': ['A','A','B','B','C','C','C']})

In [68]:
DF_obj.duplicated()

0    False
1     True
2    False
3     True
4    False
5     True
6     True
dtype: bool

In [71]:
DF_obj = DataFrame(np.arange(36).reshape(6,6))
DF_obj

    0   1   2   3   4   5
0   0   1   2   3   4   5
1   6   7   8   9  10  11
2  12  13  14  15  16  17
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

In [73]:
DF_obj2 = DataFrame(np.arange(15).reshape(5,3))
DF_obj2

    0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

In [75]:
pd.concat([DF_obj,DF_obj2], axis = 1)

    0   1   2   3   4   5     0     1     2
0   0   1   2   3   4   5   0.0   1.0   2.0
1   6   7   8   9  10  11   3.0   4.0   5.0
2  12  13  14  15  16  17   6.0   7.0   8.0
3  18  19  20  21  22  23   9.0  10.0  11.0
4  24  25  26  27  28  29  12.0  13.0  14.0
5  30  31  32  33  34  35   NaN   NaN   NaN

In [77]:
pd.concat([DF_obj,DF_obj2])

    0   1   2     3     4     5
0   0   1   2   3.0   4.0   5.0
1   6   7   8   9.0  10.0  11.0
2  12  13  14  15.0  16.0  17.0
3  18  19  20  21.0  22.0  23.0
4  24  25  26  27.0  28.0  29.0
5  30  31  32  33.0  34.0  35.0
0   0   1   2   NaN   NaN   NaN
1   3   4   5   NaN   NaN   NaN
2   6   7   8   NaN   NaN   NaN
3   9  10  11   NaN   NaN   NaN
4  12  13  14   NaN   NaN   NaN

In [79]:
DF_obj.drop([0,2])

    0   1   2   3   4   5
1   6   7   8   9  10  11
3  18  19  20  21  22  23
4  24  25  26  27  28  29
5  30  31  32  33  34  35

In [82]:
DF_obj.drop([0,2], axis = 1)

    1   3   4   5
0   1   3   4   5
1   7   9  10  11
2  13  15  16  17
3  19  21  22  23
4  25  27  28  29
5  31  33  34  35

In [85]:
series_obj = Series(np.arange(6))
series_obj.name = 'added_variable'
series_obj

0    0
1    1
2    2
3    3
4    4
5    5
Name: added_variable, dtype: int64

In [ ]:
address =