In [1]:
import numpy as np
import pandas as pd

# Viz
import matplotlib.pyplot as plt
import seaborn as sns

# Pretty plots
plt.style.use('seaborn-v0_8')
sns.set_context('notebook')

# Pandas display
pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 120)

In [2]:
df = pd.read_csv('C:/data/GitHub/BZIA_VM/DS/Halifax_transit.csv')
df.shape

(1326299, 7)

In [3]:
path = "Halifax_transit.csv"
f = open(path, "r", encoding= "utf-8")

header_line = f.readline()
print("Raw header line:", header_line)

Raw header line: ﻿OBJECTID,Route_Number,Route_Name,Ridership_Total,Route_Hour,Route_Hour_Description,Route_Date

In [4]:

header = header_line.strip().split(",")
print("Header list:", header)
print("Number of columns:", len(header))

f.close()

Header list: ['\ufeffOBJECTID', 'Route_Number', 'Route_Name', 'Ridership_Total', 'Route_Hour', 'Route_Hour_Description', 'Route_Date']
Number of columns: 7

In [5]:
df.columns

Index(['OBJECTID', 'Route_Number', 'Route_Name', 'Ridership_Total', 'Route_Hour', 'Route_Hour_Description',
       'Route_Date'],
      dtype='object')

In [6]:
df.head()

   OBJECTID Route_Number      Route_Name  Ridership_Total  Route_Hour Route_Hour_Description            Route_Date
0         1           10       Dalhousie                8         5.5       5:30am to 5:59am  1/1/2024 10:00:00 AM
1         2           22         Armdale                2         5.5       5:30am to 5:59am  1/1/2024 10:00:00 AM
2         3           6C  Heritage Hills                5         5.5       5:30am to 5:59am  1/1/2024 10:00:00 AM
3         4           90     Larry Uteck                0         5.5       5:30am to 5:59am  1/1/2024 10:00:00 AM
4         5            1   Spring Garden               21         6.0       6:00am to 6:29am  1/1/2024 10:00:00 AM

In [7]:
df.dtypes

OBJECTID                    int64
Route_Number               object
Route_Name                 object
Ridership_Total             int64
Route_Hour                float64
Route_Hour_Description     object
Route_Date                 object
dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1326299 entries, 0 to 1326298
Data columns (total 7 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   OBJECTID                1326299 non-null  int64
 1   Route_Number            1326299 non-null  object
 2   Route_Name              1326299 non-null  object
 3   Ridership_Total         1326299 non-null  int64
 4   Route_Hour              1326299 non-null  float64
 5   Route_Hour_Description  1326299 non-null  object
 6   Route_Date              1326299 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 70.8+ MB

In [9]:
df.isna().sum()

OBJECTID                  0
Route_Number              0
Route_Name                0
Ridership_Total           0
Route_Hour                0
Route_Hour_Description    0
Route_Date                0
dtype: int64

In [10]:
df['Ridership_Total']

0            8
1            2
2            5
3            0
4           21
          ...
1326294      2
1326295     13
1326296     88
1326297     92
1326298    295
Name: Ridership_Total, Length: 1326299, dtype: int64

In [36]:
r1 = df[df['Route_Number'] =='1']
r1.shape

(28322, 10)

In [12]:
r1['Ridership_Total'].reset_index(drop=True).head(10)

0     21
1     33
2     17
3     46
4    502
5     47
6     80
7    296
8     81
9    480
Name: Ridership_Total, dtype: int64

In [13]:

r1_numbers = r1["Ridership_Total"].tolist()
r1_numbers[:10]

[21, 33, 17, 46, 502, 47, 80, 296, 81, 480]

In [14]:

r1_only = r1[["Ridership_Total"]].reset_index(drop=True)
r1_only.head(10)

   Ridership_Total
0               21
1               33
2               17
3               46
4              502
5               47
6               80
7              296
8               81
9              480

In [15]:

r1_sorted = r1.sort_values(["Route_Date", "Route_Hour"])
r1_sorted[["Route_Date", "Route_Hour_Description", "Ridership_Total"]].head(10)

                 Route_Date Route_Hour_Description  Ridership_Total
20085  1/1/2024 10:00:00 AM       5:30am to 5:59am               29
4      1/1/2024 10:00:00 AM       6:00am to 6:29am               21
20100  1/1/2024 10:00:00 AM       6:30am to 6:59am               27
20112  1/1/2024 10:00:00 AM       7:00am to 7:29am               42
46     1/1/2024 10:00:00 AM       7:30am to 7:59am               33
59     1/1/2024 10:00:00 AM       8:00am to 8:29am               17
80     1/1/2024 10:00:00 AM       8:30am to 8:59am               46
20662  1/1/2024 10:00:00 AM       9:00am to 9:29am               28
20678  1/1/2024 10:00:00 AM       9:30am to 9:59am               45
228    1/1/2024 10:00:00 AM     10:00am to 10:29am               47

In [16]:

df["Route_Date"] = pd.to_datetime(df["Route_Date"], errors="coerce")
df["Route_Date"].dtype

dtype('<M8[ns]')

In [17]:
#mask = (df['Route_Number'] == '2') & (df['Year'] == 2024)
#mask

In [37]:
df[df['Route_Number'] == '2'].head()

,OBJECTID,Route_Number,Route_Name,Ridership_Total,Route_Hour,Route_Hour_Description,Route_Date,Year,Route_Number_norm,Route_Name_norm
5,6,2,Fairview,34,6.0,6:00am to 6:29am,2024-01-01 10:00:00,2024,2,FAIRVIEW
16,17,2,Fairview,15,6.5,6:30am to 6:59am,2024-01-01 10:00:00,2024,2,FAIRVIEW
47,48,2,Fairview,30,7.5,7:30am to 7:59am,2024-01-01 10:00:00,2024,2,FAIRVIEW
137,138,2,Fairview,199,16.5,4:30pm to 4:59pm,2024-01-08 10:00:00,2024,2,FAIRVIEW
189,190,2,Fairview,31,9.0,9:00am to 9:29am,2024-01-01 10:00:00,2024,2,FAIRVIEW

In [39]:
df['Year'] = pd.to_datetime(df['Route_Date']).dt.year

In [19]:
pd.to_datetime(df["Route_Date"], errors="coerce").dtype

dtype('<M8[ns]')

In [20]:
df["Route_Date"].isna().sum()  # how many became NaT (if any)

np.int64(0)

In [21]:
df['Year'] = df['Route_Date'].dt.year
df[['Route_Date', 'Year']].head(5)

           Route_Date  Year
0 2024-01-01 10:00:00  2024
1 2024-01-01 10:00:00  2024
2 2024-01-01 10:00:00  2024
3 2024-01-01 10:00:00  2024
4 2024-01-01 10:00:00  2024

In [22]:
df.groupby("Year")["Ridership_Total"].sum()

Year
2024    30653970
2025    30069008
2026      909704
Name: Ridership_Total, dtype: int64

In [23]:
df.groupby("Year")["Ridership_Total"].mean()

Year
2024    47.332024
2025    45.844730
2026    39.944849
Name: Ridership_Total, dtype: float64

In [24]:
df['Ridership_Total'].sum()

np.int64(61632682)

In [25]:
df['Ridership_Total'].mean()

np.float64(46.46967388198287)

In [26]:
#“Which routes are most used?”
df.groupby('Route_Number')['Ridership_Total'].sum()

Route_Number
1      5378092
10     1293395
10A     280469
10B     836702
10C    1369596
        ...
90     1946035
91      762912
93      128166
9A     2700419
9B     1581333
Name: Ridership_Total, Length: 80, dtype: int64

In [27]:
df['Route_Number'].nunique()

80

In [28]:
len(df['Route_Number'].unique())

80

In [29]:
df.groupby('Route_Number')['Ridership_Total'].sum().sort_values(ascending=False).head(10)

Route_Number
1     5378092
3     5036132
2     3549295
8     3326258
4     3153841
9A    2700419
5     2674204
29    1960863
90    1946035
7A    1623399
Name: Ridership_Total, dtype: int64

In [30]:

Route_mean = df.groupby("Route_Number")["Ridership_Total"].mean()
Route_mean.head

<bound method NDFrame.head of Route_Number
1      189.890968
10     105.859797
10A     61.077744
10B     59.260713
10C     82.800073
          ...
90      81.430873
91      35.257972
93      19.445608
9A     109.996701
9B      69.493869
Name: Ridership_Total, Length: 80, dtype: float64>

In [31]:
#ENTENDER E RECRIAR ESSE STEP AQUI
Route_mean_df = (
    df.groupby("Route_Number", as_index=False)["Ridership_Total"]
      .mean()
      .rename(columns={"Ridership_Total": "ridership_mean"})
      .sort_values("ridership_mean", ascending=False)
)
Route_mean_df.head(10)

   Route_Number  ridership_mean
0             1      189.890968
32            3      171.828858
24            2      123.303630
67            8      114.583968
39            4      110.571854
78           9A      109.996701
1            10      105.859797
43            5       91.366429
4           10C       82.800073
75           90       81.430873

In [32]:

# 1) Normalize
df['Route_Number_norm'] = df['Route_Number'].str.strip().str.upper()
df['Route_Name_norm']   = df['Route_Name'].str.strip().str.upper()

# 2) Distinct pairs (like “distinct rows” of number+name)
RouteNumName = df[['Route_Number_norm', 'Route_Name_norm']].drop_duplicates()

# 3) Count them
RouteNumName.shape[0]   # → should be 91

# str.strip().str.upper() >> Clean text by removing extra spaces and making everything UPPERCASE, 
# so ‘small differences’ don’t create fake distinct values.

91

In [33]:

# Distinct counts
df['Route_Number'].nunique()                               # 80
df['Route_Name'].nunique()                                 # 89
df[['Route_Number','Route_Name']].drop_duplicates().shape  # (92, 2)

(92, 2)

In [34]:
# Case-insensitive distinct pairs
(df.assign(Route_Number_norm=df['Route_Number'].str.strip().str.upper(),
           Route_Name_norm=df['Route_Name'].str.strip().str.upper())
   [['Route_Number_norm','Route_Name_norm']]
   .drop_duplicates()
   .shape)  # → (91, 2)

(91, 2)

In [42]:
df['Year'] = pd.to_datetime(df['Route_Date']).dt.year
df['Year'].head()

0    2024
1    2024
2    2024
3    2024
4    2024
Name: Year, dtype: int32

In [62]:
mask = (df['Route_Number'] == '2') & (df['Year'] == 2024)
mask

0          False
1          False
2          False
3          False
4          False
           ...
1326294    False
1326295    False
1326296    False
1326297    False
1326298    False
Length: 1326299, dtype: bool

In [66]:
mask.any()

np.True_

In [67]:
total_2024_route2 = df.loc[mask, 'Ridership_Total'].sum()
total_2024_route2

np.int64(1774271)

In [80]:
by_route_year = df.groupby(['Route_Number', 'Year'], as_index=False)['Ridership_Total'].sum()

In [81]:
by_route_year[(by_route_year['Route_Number'] == '2') & (by_route_year['Year'] == 2024)]

   Route_Number  Year  Ridership_Total
70            2  2024          1774271

In [71]:
df['Route_Number'].dtype

dtype('O')

In [72]:
df['Route_Number'] = df['Route_Number'].astype(str).str.strip()

In [73]:

df['Year'] = pd.to_datetime(df['Route_Date']).dt.year
df['Route_Number'] = df['Route_Number'].astype(str).str.strip()

In [75]:

mask = (df['Route_Number'] == '2') & (df['Year'] == 2024)
mask.sum()

np.int64(14161)

In [88]:

df.groupby(['Route_Number','Year'], as_index=False)['Ridership_Total'].sum()\
  .query("Route_Number == '2' and Year == 2024")

   Route_Number  Year  Ridership_Total
70            2  2024          1774271

In [91]:
by_route_year = df.groupby(['Route_Number','Year'], as_index=False)['Ridership_Total'].agg(['sum','mean']).reset_index()
by_route_year

     index Route_Number  Year      sum        mean
0        0            1  2024  2710271  197.700124
1        1            1  2025  2583389  183.063279
2        2            1  2026    84432  168.526946
3        3           10  2024  1293395  105.859797
4        4          10A  2024    25266   52.637500
..     ...          ...   ...      ...         ...
231    231           9A  2025  1319188  109.476183
232    232           9A  2026    38936   94.965854
233    233           9B  2024   789653   70.479561
234    234           9B  2025   768263   68.791458
235    235           9B  2026    23417   61.140992

[236 rows x 5 columns]

In [92]:
by_route_year.query("Route_Number == '2' and Year == 2024")

    index Route_Number  Year      sum        mean
70     70            2  2024  1774271  125.292776

In [95]:
by_route_year = by_route_year.rename(columns={'sum':'Ridership_Sum','mean':'Ridership_Mean'})
by_route_year

     index Route_Number  Year  Ridership_Sum  Ridership_Mean
0        0            1  2024        2710271      197.700124
1        1            1  2025        2583389      183.063279
2        2            1  2026          84432      168.526946
3        3           10  2024        1293395      105.859797
4        4          10A  2024          25266       52.637500
..     ...          ...   ...            ...             ...
231    231           9A  2025        1319188      109.476183
232    232           9A  2026          38936       94.965854
233    233           9B  2024         789653       70.479561
234    234           9B  2025         768263       68.791458
235    235           9B  2026          23417       61.140992

[236 rows x 5 columns]

In [97]:
df.groupby(['Route_Number','Year'], as_index=False)['Ridership_Total'].sum()\
  .query("Route_Number == '3' and Year == 2024")

   Route_Number  Year  Ridership_Total
94            3  2024          2639674

In [107]:
df.groupby(['Route_Name'], as_index=False)['Ridership_Total'].sum().sort_values("Ridership_Total", ascending=False)

                           Route_Name  Ridership_Total
72                      Spring Garden          5378092
32                           Fairview          3549295
23                          CrossTown          3436291
70                 Sackville Corridor          3326258
82                       Universities          3153841
..                                ...              ...
75                         Springvale            27110
67              Preston- Porters Lake            25922
78  Tantallon - Sheldrake Lake MetroX            22870
62          Porters Lake Regional Exp            14558
65                   Portland Estates             6514

[89 rows x 2 columns]

In [109]:
df.groupby(['Route_Name'], as_index=False)['Ridership_Total'].agg(['sum','mean']).sort_values("sum", ascending=False)

                           Route_Name      sum        mean
72                      Spring Garden  5378092  189.890968
32                           Fairview  3549295  123.303630
23                          CrossTown  3436291  169.367194
70                 Sackville Corridor  3326258  114.583968
82                       Universities  3153841  110.571854
..                                ...      ...         ...
75                         Springvale    27110    6.162764
67              Preston- Porters Lake    25922   10.062888
78  Tantallon - Sheldrake Lake MetroX    22870   20.328889
62          Porters Lake Regional Exp    14558    6.828330
65                   Portland Estates     6514    4.413279

[89 rows x 3 columns]